[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-mixed"
version = "2.1.1"
description = "Implements a dummy function combining rust and python"
readme = "Readme.md"
edition = "2018"

[package.metadata.maturin.scripts]
get_42 = "pyo3_mixed:get_42"

[dependencies]
pyo3 = { version = "0.8.1", features = ["extension-module"] }

[lib]
name = "pyo3_mixed"
crate-type = ["cdylib"]
